language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=cover
        - python: 3.7
          env: TOXENV=cover3
          dist: xenial          # required for Python >= 3.7
        - python: 3.7
          env: TOXENV=docs
          dist: xenial          # required for Python >= 3.7
        - python: 2.7
          env:
            - TOXENV=py27
            - END_TO_END=1
        - python: 2.7
          env:
            - TOXENV=py27-configparser
            - END_TO_END=1
        - python: 3.4
          env:
            - TOXENV=py34
            - END_TO_END=1
        - python: 3.5
          env:
            - TOXENV=py35
            - END_TO_END=1
        - python: 3.6
          env:
            - TOXENV=py36
            - END_TO_END=1
        - python: 3.7
          env:
            - TOXENV=py37
            - END_TO_END=1
          dist: xenial          # required for Python >= 3.7

        - python: 3.8
          env:
            - TOXENV=py38
            - END_TO_END=1
          dist: xenial          # required for Python >= 3.7

        - name: "Python: 3.7 on macOS"
          language: sh          # 'language: python' is not yet supported on Travis CI macOS
          os: osx
          osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
          env:
            - TOXENV=py37
            - END_TO_END=1

        - name: "Python 3.7.5 on Windows"
          os: windows           # Windows 10.0.17134 N/A Build 17134
          language: shell       # 'language: python' is an error on Travis CI Windows
          # python: 3.7         # 'python:' is ignored on Travis CI Windows
          before_install:
            # https://travis-ci.community/t/windows-python-pip-module-not-found/5480/4
            - choco install python  --version 3.7.5
            - python -m pip install --upgrade pip
            - python -m pip install pywin32
            # According to Supervisor/supervisor, pexpect is installed on Linux by tox.			
            # pexpect==4.7.0
            - python -m pip install pexpect
          env:
            - PATH=/c/Python37:/c/Python37/Scripts:$PATH
            - TOXENV=py37


install:
    - travis_retry pip install virtualenv tox pexpect

script:
    - travis_retry tox
